name: BlazinVanish
author: iiFlamiinBlaze
version: 1.0.4
description: An advanced survival vanish plugin for PocketMine
api: 3.0.0
main: iiFlamiinBlaze\BlazinVanish\BlazinVanish
commands:
 vanish:
  permission: blazinvanish.command
  description: "Allows the player to vanish"
permissions:
 blazinvanish.command:
  default: op
 blazinvanish.other:
  default: op